blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
# post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail, name='post_detail'),
    #path to display posts with tags
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone 
from django.contrib.auth.models import User 
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager): 
    def get_queryset(self): 
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model): 
    STATUS_CHOICES = ( 
        ('draft', 'Draft'), 
        ('published', 'Published'), 
    ) 
    title = models.CharField(max_length=250) 
    slug = models.SlugField(max_length=250,  
                            unique_for_date='publish') 
    author = models.ForeignKey(User, 
                               on_delete=models.CASCADE,
                               related_name='blog_posts') 
    body = models.TextField() 
    publish = models.DateTimeField(default=timezone.now) 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    status = models.CharField(max_length=10,  
                              choices=STATUS_CHOICES, 
                              default='draft') 
    featured_image = models.ImageField(upload_to='featured_image/%Y/%m/%d/') 

    
    objects = models.Manager() # The default manager. 
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()

    class Meta: 
        ordering = ('-publish',) 

    def __str__(self): 
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model): 
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80) 
    email = models.EmailField() 
    body = models.TextField() 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True) 
 
    class Meta: 
        ordering = ('created',) 
 
    def __str__(self): 
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from django.forms import ModelForm, TextInput, EmailInput, Textarea
from .models import Comment

#post sharing form
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
    widget=forms.Textarea)

#post comment form
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email', 'body')
        widgets = {
            'name': TextInput(attrs={
                'class': "w-full px-3 py-2 pt-5 pb-2 border border-gray-200 rounded appearance-none input focus focus:border-indigo-600 focus:outline-none active:outline-none active:border-indigo-600",
                
                'placeholder': 'Name'
                }),
            'email': EmailInput(attrs={
                'class': "w-full px-3 py-3 pt-5 pb-2 border border-gray-200 rounded appearance-none input focus focus:border-indigo-600 focus:outline-none active:outline-none active:border-indigo-600", 
                
                'placeholder': 'Email'
                }),
            'body': Textarea(attrs={
                'class': "w-full px-4 py-3 mb-4 border border-2 border-transparent border-gray-200 rounded-lg focus:ring focus:ring-blue-500 focus:outline-none", 
                
                'placeholder': 'Write your comment here'
                })
        }




        

blog/views.py
# Create your views here.

from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
#JsonResponse to return json objects used in infinite scroll
# from django.http import JsonResponse
from django.views.generic import ListView
from .models import Post, Comment
from .forms import CommentForm
from taggit.models import Tag
from django.db.models import Count

#function based view without pagination
# def post_list(request):
#     posts = Post.published.all()
#     return render(request,'blog/post/list.html',{'posts': posts})

#post detail view without comments
# def post_detail(request, year, month, day, post):
#     post = get_object_or_404(Post, slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
#     return render(request,'blog/post/detail.html',{'post': post})

#post detail view with comments
# def post_detail(request, year, month, day, post):
#     post = get_object_or_404(Post, slug=post,
#                                    status='published',
#                                    publish__year=year,
#                                    publish__month=month,
#                                    publish__day=day)
    
#     # List of active comments for this post
#     comments = post.comments.filter(active=True)

#     new_comment = None

#     if request.method == 'POST':
#         # A comment was posted
#         comment_form = CommentForm(data=request.POST)
#         if comment_form.is_valid():
#             # Create Comment object but don't save to database yet
#             new_comment = comment_form.save(commit=False)
#             # Assign the current post to the comment
#             new_comment.post = post
#             # Save the comment to the database
#             new_comment.save()
#     else:
#         comment_form = CommentForm()
    
#     # List of similar posts
#     post_tags_ids = post.tags.values_list('id', flat=True)
#     similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
#     similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

#     return render(request,
#                   'blog/post/detail.html',
#                   {'post': post,
#                    'comments': comments,
#                    'new_comment': new_comment,
#                    'comment_form': comment_form,
#                    'similar_posts': similar_posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:3]

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


#function based view with pagination
def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 2) # 2 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:     
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,'blog/post/list.html',{'page': page,'posts': posts, 'tag': tag})


# def post_list(request, tag_slug=None):
#     object_list = Post.published.all()
#     tag = None

#     if tag_slug:
#         tag = get_object_or_404(Tag, slug=tag_slug)
#         object_list = object_list.filter(tags__in=[tag])

#     paginator = Paginator(object_list, 3) # 3 posts in each page
#     page = request.GET.get('page')
#     try:
#         posts = paginator.page(page)
#     except PageNotAnInteger:
#         # If page is not an integer deliver the first page
#         posts = paginator.page(1)
#     except EmptyPage:
#         # If page is out of range deliver last page of results
#         posts = paginator.page(paginator.num_pages)

#     return render(request,
#                   'blog/post/list.html',
#                   {'page': page,
#                    'posts': posts,
#                    'tag': tag})


#class based view with pagination
# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 2
#     template_name = 'blog/post/list.html'

    

blog/templates/blog/post/detail copy.html
{% extends "blog/base.html" %}


{% block title %}
    {{ post.title }}
{% endblock %}

<div class="mt-6 bg-gray-50">
<!--posts by this author block to be included here-->
<!--end posts by this author block-->
    <div class=" px-10 py-6 mx-auto">

            {% block content %}
             <!--post-featured-image-->
                <div class="max-w-6xl px-10 py-6 mx-auto bg-gray-50">
                        
		                <!--<a href="#_" class="block transition duration-200 ease-out transform hover:scale-110">
	                        <img class="object-cover w-full shadow-sm h-full" src="../static/username.png">
	                    </a>-->
                        <!--post categories-->
		                <!--<div class="flex items-center justify-start mt-4 mb-4">
                        	<a href="#"class="px-2 py-1 font-bold bg-red-400 text-white rounded-lg hover:bg-gray-500 mr-4">Django</a>
                        	<a href="#"class="px-2 py-1 font-bold bg-red-400 text-white rounded-lg hover:bg-gray-500 mr-4">Python</a>
                        	<a href="#"class="px-2 py-1 font-bold bg-red-400 text-white rounded-lg hover:bg-gray-500">web development</a>
                         </div>-->
                        <div class="mt-2">
                        	<!--post heading-->
                        	<h2 class="sm:text-3xl md:text-3xl lg:text-3xl xl:text-4xl font-bold text-purple-500  hover:underline">{{ post.title }}</h2>

                                <!--post views-->
                                <!--<div class="flex justify-start items-center mt-2">
                                	<p class="text-sm text-green-500 font-bold bg-gray-100 rounded-full py-2 px-2 hover:text-red-500">3000</p>
                                	<p class="text-sm text-gray-400 font-bold ml-5">Views</p>
                                
                                </div>-->

                                <!--author avator-->
                               <div class="font-light text-gray-600">
	                              
	                        		<a href="#" class="flex items-center mt-6 mb-6">
                                    <!--<img
	                                        src="../static/teach.jpg"
	                                        alt="avatar" class="hidden object-cover w-14 h-14 mx-4 rounded-full sm:block">-->
	                                    <h1 class="font-bold text-gray-700 hover:underline">By {{ post.author }}</h1><span>Published {{ post.publish }}</span>
	                                </a>
                        	  </div>
                       </div>

                               	<!--post content-->
                 <div class="max-w-4xl px-10  mx-auto text-2xl text-gray-700 mt-4 rounded bg-gray-100">

                 	<!--content body-->
                 	<div>
                        	<p class="mt-2 p-8 ">{{ post.body|linebreaks }}</p>
                     </div>

                     

				        </div>
                    
                    
                </div>
            
            {% endblock %}
    </div>

</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}


{% block title %}
    {{ post.title }}
{% endblock %}

<div class="mt-6 bg-gray-50">
<!--posts by this author block to be included here-->
<!--end posts by this author block-->
    <div class=" px-10 py-6 mx-auto">

            {% block content %}
             <!--post-featured-image-->
                <div class="max-w-6xl px-10 py-6 mt-8 mx-auto bg-gray-50">
                       
                        <div class="mt-2">
                        <!-- featured image-->
                        <a href="#_" class="block transition duration-200 ease-out transform hover:scale-110">
                              <img class="object-cover w-full shadow-sm " src="{{ post.featured_image.url }}"
                                alt="{{post.title}}">
                          </a>


                              <!--post tags-->
		                      <div class="flex items-center justify-start mt-4 mb-4">
                            {% for tag in post.tags.all %}
                        	  <a href="{% url "blog:post_list_by_tag" tag.slug %}"class="px-2 py-1 font-bold bg-red-400 text-white rounded-lg hover:bg-gray-500 mr-4">{{ tag.name }}</a>
                            {% if not forloop.last %} {% endif %} 
                            {% endfor %}
                          </div>

                        	<!--post heading-->
                        	<h2 class="sm:text-3xl md:text-3xl lg:text-3xl xl:text-4xl font-bold text-purple-500  hover:underline">{{ post.title }}</h2>
                            

                                <!--author avator-->
                               <div class="font-light text-gray-600">
	                              
	                        		<a href="#" class="flex items-center mt-6 mb-6">
	                                    <h1 class="font-bold text-gray-700 hover:underline">By {{ post.author }}</h1><span>Published {{ post.publish }}</span>
	                                </a>
                              
                        	  </div>
                            
                       </div>
                            <!--post content-->
                 <div class="max-w-4xl px-10  mx-auto text-2xl text-gray-700 mt-4 rounded bg-gray-100">

                 	<!--content body-->
                 	<div>
                    <p class="mt-2 p-8 ">{{ post.body|linebreaks }}</p>
                </div>
			</div>

    <!--related posts-->          
       
      
        <h2 class="text-2xl mt-12 text-gray-500 font-bold text-center">Related Posts</h2>
          <div class="flex items-center mt-8 w-full px-8 py-6  text-center">
          {% for post in similar_posts %}
          
            <div class="">
              
              <!-- featured image-->
		                <a href="#_" class="block transition duration-200 ease-out transform hover:scale-110">
	                        <img class="object-cover w-full shadow-sm max-h-80" src="{{ post.featured_image.url }}"
                            alt="{{post.title}}">
	                    </a>
            
              <div class="relative flex flex-col items-start px-6 bg-white border border-t-0 border-gray-200 py-7 rounded-b-2xl">
                <h2 class="text-base text-gray-500 font-bold sm:text-lg md:text-xl"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>  
              </div>

            </div>
              {% empty %}
              There are no posts related to this one yet.
          
          {% endfor %}
        </div>
 
    <!--end related posts-->
    		    
    
<!--comment success message-->
      {% if new_comment %}
          <!--success message-->
        <div class="w-full text-white bg-green-500 mt-4">
          <div class="container flex items-center justify-between px-6 py-4 mx-auto">
            <div class="flex">
                <svg viewBox="0 0 40 40" class="w-6 h-6 fill-current">
                    <path d="M20 3.33331C10.8 3.33331 3.33337 10.8 3.33337 20C3.33337 29.2 10.8 36.6666 20 36.6666C29.2 36.6666 36.6667 29.2 36.6667 20C36.6667 10.8 29.2 3.33331 20 3.33331ZM16.6667 28.3333L8.33337 20L10.6834 17.65L16.6667 23.6166L29.3167 10.9666L31.6667 13.3333L16.6667 28.3333Z"></path>
                </svg>

                <p class="mx-3">Your comment has been added.</p>
            </div>
            <button class="p-1 transition-colors duration-200 transform rounded-md hover:bg-opacity-25 hover:bg-gray-600 focus:outline-none">
                <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M6 18L18 6M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
            </button>
          </div>
      </div>
      <!--end success message-->
      <!--comment form-->
            {% else %}
          <div class="max-w-4xl py-16 xl:px-8 flex justify-center mx-auto">
            <div class="w-full mt-16 md:mt-0 ">
              <form action="." method="post" class="relative z-10 h-auto p-8 py-10 overflow-hidden bg-white border-b-2 border-gray-300 rounded-lg shadow-2xl px-7">
                <h3 class="mb-6 text-2xl font-medium text-center">Write a comment</h3>
                {{ comment_form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Submit comment" class=" text-white px-4 py-3 bg-blue-500  rounded-lg">
              </form>
              </div>
          </div>
        {% endif %} 
    <!--end comment form-->
    	<!--comments count-->
		<div class="max-w-4xl px-10 py-16 mx-auto bg-gray-100  bg-white min-w-screen animation-fade animation-delay  px-0 px-8 mx-auto sm:px-12 xl:px-5">
		    {% with comments.count as total_comments %}
          <p class="mt-1 text-2xl font-bold text-left text-gray-800 sm:mx-6 sm:text-2xl md:text-3xl lg:text-4xl sm:text-center sm:mx-0">
             We have {{ total_comments }} comment{{ total_comments|pluralize }} on this post</p> 
          {% endwith %}
        <!--end comments count-->
        <!--comments display-->
          {% for comment in comments %}
        
		        <!--comment 1-->
            
		        <div class="flex  items-center w-full px-6 py-6 mx-auto mt-10 bg-white border border-gray-200 rounded-lg sm:px-8 md:px-12 sm:py-8 sm:shadow lg:w-5/6 xl:w-2/3">
                
		        	{% comment %} <a href="#" class="flex items-center mt-6 mb-6 mr-6"><img src="../static/teach.jpg" alt="avatar" class="hidden object-cover w-14 h-14 mx-4 rounded-full sm:block">
			        </a> {% endcomment %}
                   
		            <div><h3 class="text-lg font-bold text-purple-500 sm:text-xl md:text-2xl">Comment {{ forloop.counter }} by {{ comment.name }}</h3>
		            	<p class="text-sm font-bold text-gray-300">{{ comment.created }}</p>
		            	<p class="mt-2 text-base text-gray-600 sm:text-lg md:text-normal"> {{ comment.body|linebreaks }}</p>
		            </div>
		            
		        </div>
            
              {% endfor %}
		<!--end comments display--> 
          </div>
		    </div>

    {% endblock %}
  </div>

</div>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}

{% block content %}
<div class="w-full lg:w-6/12">
<!--blog filter area-->
    <div class="flex items-center justify-between mb-8">
                    <h1 class="text-xl font-bold text-green-700 md:text-2xl">Posts</h1>

                    <!--posts filter-->
                    <div>
                        <select class="w-full text-green-500 border-gray-300 p-2 rounded-md shadow-sm focus:border-green-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
                            <option class="text-green-500 ">Latest</option>
                            <option class="text-green-500 ">Last Week</option>
                        </select>
                    </div>
        </div>

        {% if tag %}
            <h2 >All posts tagged <span class="font-bold text-red-500 ">"{{ tag.name }}"</span></h2>
        {% endif %}
        
        {% for post in posts %}
        <div class="mt-2">

         

          <!---posts area-->
                <div class="mt-6">
                    <div class="max-w-4xl px-10 py-6 mx-auto bg-white rounded-lg shadow-md">
                        <div class="flex items-center justify-between mb-4">
                        	<span class="font-light text-gray-600">
                        		<a href="#" class="flex items-center">
                                <!--blog author infomation-->
                                <img src="{{ post.featured_image.url }}"
                                        alt="{{post.title}}" class="hidden object-cover w-10 h-10 mx-4 rounded-full sm:block">
                                    <h1 class="font-bold text-gray-700 hover:underline">{{ post.author }}</h1>
                                </a>
                        	</span>
                            <!--blog tags-->
                             {% for tag in post.tags.all %}
                                <a href="{% url "blog:post_list_by_tag" tag.slug %}"class="px-2 py-1 font-bold bg-red-500 text-white rounded-lg hover:bg-gray-500">
                                {{ tag.name }}
                                </a>
                                {% if not forloop.last %} {% endif %} 
                              {% endfor %}
                            
                        </div>

                        <!-- featured image-->
		                <a href="#_" class="block transition duration-200 ease-out transform hover:scale-110">
	                        <img class="object-cover w-full shadow-sm max-h-80" src="{{ post.featured_image.url }}"
                            alt="{{post.title}}">
	                    </a>
                        <div class="mt-2">
                        <a href="{{ post.get_absolute_url }}"class="sm:text-3xl md:text-3xl lg:text-3xl xl:text-4xl font-bold text-purple-500  hover:underline">{{ post.title }}</a>
                            
                            <!--post body-->
                            <p class="mt-2 text-gray-500">{{ post.body|truncatewords:20|linebreaks }}</p>
                        </div>
                        <div class="flex items-center justify-between mt-4">

                        	<!-- <p class="text-sm text-green-500 font-bold bg-gray-100 rounded-full py-2 px-2 hover:text-red-500">
                            Published {{ post.publish }} 
                            </p> -->

                         <div class="flex items-center">
                        <div class="relative flex items-center justify-center space-x-3">
                        <!--placeholder for social share handles-->
                        
                      </div>
                  	</div>
                    </div>
                   </div>
                </div>
         </div>
        {% endfor %}
    <!--pagination using function based view-->
    {% include "pagination.html" with page=posts %}
    
    
    </div>

 {% endblock %}

blog/templates/blog/post/posts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        #content{
            margin: 0 auto;
            width: 40vw;
        }
    </style>
</head>

<body>
    <div id="content">
        {% for post in posts %}
            <div>
                <h1>{{post.title}}</h1>
                <p>{{post.body}}</p>
            </div>
        {% endfor %}
    </div>
</body>
<script type="text/javascript" src="{% static 'blog/js/main.js' %}"></script>

</html>